# Generated by Django 3.2 on 2025-08-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_auto_20250817_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(default='1990-01-01'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
