# Generated by Django 3.2 on 2025-08-17 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(unique=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', models.TextField(help_text='Datos del bloque en formato JSON')),
                ('previous_hash', models.CharField(max_length=64)),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('nonce', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('principio_activo', models.CharField(max_length=200)),
                ('concentracion', models.CharField(max_length=50)),
                ('forma_farmaceutica', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('tipo_sangre', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('blockchain_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('ultimo_bloque_actualizado', models.CharField(blank=True, max_length=64, null=True)),
                ('fecha_ultimo_hash', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(choices=[('cardiologia', 'Cardiología'), ('dermatologia', 'Dermatología'), ('endocrinologia', 'Endocrinología'), ('gastroenterologia', 'Gastroenterología'), ('ginecologia', 'Ginecología'), ('neurologia', 'Neurología'), ('nutricion', 'Nutrición'), ('oftalmologia', 'Oftalmología'), ('pediatria', 'Pediatría'), ('psiquiatria', 'Psiquiatría'), ('traumatologia', 'Traumatología'), ('urologia', 'Urología'), ('medicina_general', 'Medicina General')], max_length=50)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('consultorio', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('confirmado', 'Confirmado'), ('en_curso', 'En Curso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado'), ('no_asistio', 'No Asistió')], default='programado', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='blockchain.paciente')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='blockchain.profesional')),
            ],
            options={
                'ordering': ['fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('dosis', models.CharField(blank=True, max_length=100)),
                ('frecuencia', models.CharField(blank=True, max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('blockchain_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('medicamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blockchain.medicamento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='blockchain.paciente')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.profesional')),
            ],
        ),
        migrations.CreateModel(
            name='PruebaLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_prueba', models.CharField(max_length=200)),
                ('fecha_realizacion', models.DateField()),
                ('resultados', models.TextField()),
                ('valores_referencia', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('archivo_resultado', models.FileField(blank=True, null=True, upload_to='pruebas_laboratorio/')),
                ('blockchain_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas', to='blockchain.paciente')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.profesional')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_registro', models.CharField(max_length=50)),
                ('contenido', models.TextField()),
                ('hash_registro', models.CharField(max_length=64, unique=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('verificado', models.BooleanField(default=False)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blockchain.block')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='CondicionMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_diagnostico', models.DateField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('controlada', 'Controlada'), ('remision', 'En Remisión'), ('curada', 'Curada')], default='activa', max_length=20)),
                ('blockchain_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condiciones', to='blockchain.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Cirugia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cirugia', models.CharField(max_length=200)),
                ('fecha_cirugia', models.DateField()),
                ('descripcion', models.TextField()),
                ('complicaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('postergada', 'Postergada')], default='programada', max_length=20)),
                ('blockchain_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cirugias', to='blockchain.paciente')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.profesional')),
            ],
        ),
        migrations.CreateModel(
            name='BlockchainTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.CharField(max_length=100)),
                ('to_address', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('signature', models.TextField(blank=True)),
                ('medical_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blockchain.medicalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Antecedente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('familiar', 'Familiar'), ('personal', 'Personal'), ('quirurgico', 'Quirúrgico'), ('alergico', 'Alérgico'), ('farmacologico', 'Farmacológico')], max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha_evento', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('blockchain_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes', to='blockchain.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Alergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sustancia', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('severidad', models.CharField(choices=[('leve', 'Leve'), ('moderada', 'Moderada'), ('grave', 'Grave'), ('muy_grave', 'Muy Grave')], default='leve', max_length=20)),
                ('fecha_diagnostico', models.DateField()),
                ('blockchain_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alergias', to='blockchain.paciente')),
            ],
        ),
    ]
