# Generated by Django 3.2 on 2025-08-17 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='telefono',
        ),
    ]
