# Generated by Django 3.2 on 2025-08-27 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_fix_fks'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blockchainhash',
            unique_together=set(),
        ),
    ]
