# Generated by Django 3.2 on 2025-08-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_add_missing_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condicionmedica',
            old_name='nombre',
            new_name='codigo',
        ),
        migrations.RemoveField(
            model_name='blockchaintransaction',
            name='medical_record',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
    ]
