# Generated by Django 3.2 on 2025-08-17 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0004_remove_medicalrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlockchainTransaction',
        ),
    ]
