# Generated by Django 3.2 on 2025-08-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='nombres',
        ),
        migrations.AddField(
            model_name='profesional',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profesional',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profesional',
            name='direccion',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
