# Generated by Django 3.2 on 2025-08-30 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20250827_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('principio_activo', models.CharField(max_length=200)),
                ('concentracion', models.CharField(max_length=50)),
                ('forma_farmaceutica', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('confirmado', 'Confirmado'), ('en_curso', 'En Curso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado'), ('no_asistio', 'No Asistió')], default='programado', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='users.paciente')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='users.profesional')),
            ],
            options={
                'ordering': ['fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('dosis', models.CharField(blank=True, max_length=100)),
                ('frecuencia', models.CharField(blank=True, max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('medicamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.medicamento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='users.paciente')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profesional')),
            ],
        ),
        migrations.CreateModel(
            name='PruebaLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_prueba', models.CharField(max_length=200)),
                ('fecha_realizacion', models.DateField()),
                ('resultados', models.TextField()),
                ('valores_referencia', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('archivo_resultado', models.FileField(blank=True, null=True, upload_to='pruebas_laboratorio/')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas', to='users.paciente')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profesional')),
            ],
        ),
        migrations.CreateModel(
            name='CondicionMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_diagnostico', models.DateField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('controlada', 'Controlada'), ('remision', 'En Remisión'), ('curada', 'Curada')], default='activa', max_length=20)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condiciones', to='users.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Cirugia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cirugia', models.CharField(max_length=200)),
                ('fecha_cirugia', models.DateField()),
                ('descripcion', models.TextField()),
                ('complicaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('postergada', 'Postergada')], default='programada', max_length=20)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cirugias', to='users.paciente')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profesional')),
            ],
        ),
        migrations.CreateModel(
            name='Antecedente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('familiar', 'Familiar'), ('personal', 'Personal'), ('quirurgico', 'Quirúrgico'), ('alergico', 'Alérgico'), ('farmacologico', 'Farmacológico')], max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha_evento', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes', to='users.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Alergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sustancia', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('severidad', models.CharField(choices=[('leve', 'Leve'), ('moderada', 'Moderada'), ('grave', 'Grave'), ('muy_grave', 'Muy Grave')], default='leve', max_length=20)),
                ('fecha_diagnostico', models.DateField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alergias', to='users.paciente')),
            ],
        ),
    ]
