# Generated by Django 3.2 on 2025-08-30 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alergia_antecedente_cirugia_condicionmedica_medicamento_pruebalaboratorio_tratamiento_turno'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('genesis', 'Hash Génesis'), ('alergia', 'Alergia'), ('condicion', 'Condición Médica'), ('tratamiento', 'Tratamiento'), ('antecedente', 'Antecedente'), ('prueba_laboratorio', 'Prueba de Laboratorio'), ('cirugia', 'Cirugía')], max_length=20)),
                ('record_id', models.PositiveIntegerField()),
                ('hash_value', models.CharField(max_length=64, unique=True)),
                ('transaction_hash', models.CharField(blank=True, max_length=66)),
                ('block_number', models.PositiveIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('datos_originales', models.JSONField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_hashes', to='users.paciente')),
            ],
            options={
                'verbose_name': 'Blockchain Hash',
                'verbose_name_plural': 'Blockchain Hashes',
                'ordering': ['-timestamp'],
                'unique_together': {('paciente', 'categoria', 'record_id')},
            },
        ),
        migrations.CreateModel(
            name='AccesoBlockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_acceso', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('motivo_acceso', models.TextField(blank=True)),
                ('hash_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to='users.blockchainhash')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profesional')),
            ],
            options={
                'verbose_name': 'Acceso Blockchain',
                'verbose_name_plural': 'Accesos Blockchain',
                'ordering': ['-fecha_acceso'],
            },
        ),
    ]
