# Generated by Django 4.2.16 on 2025-08-30 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_accesoblockchain_blockchainhash'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesoblockchain',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.paciente'),
        ),
        migrations.AlterField(
            model_name='accesoblockchain',
            name='profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profesional'),
        ),
    ]
