from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class ChatMessage(models.Model):
    """Modelo para almacenar mensajes del chat"""
    user = models.ForeignKey(
        User, 
        on_delete=models.CASCADE, 
        null=True,  # Permitir NULL temporalmente
        blank=True,  # Permitir vacío en formularios
        verbose_name="Usuario"
    )
    user_message = models.TextField(verbose_name="User message", help_text="Message sent by the user")
    ai_response = models.TextField(verbose_name="AI response", help_text="Response generated by the AI")
    timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Date and time")
    created_at = models.DateTimeField(default=timezone.now, verbose_name="Creation date")
    session_key = models.CharField(
        max_length=40, 
        null=True, 
        blank=True, 
        help_text="User session ID",
        verbose_name="User session ID"
    )
    
    class Meta:
        verbose_name = "Chat Message"
        verbose_name_plural = "Chat Messages"
        ordering = ['-timestamp', '-created_at']
    
    def __str__(self):
        username = self.user.username if self.user else "Anonymous"
        return f"{username} - {self.timestamp.strftime('%Y-%m-%d %H:%M')}"